### ISSUE TITLE
Bullet Proofing LCA `nodes_dmp` `taxid_lineage_dump`

### ISSUE THREAD

**Issue by cbird808** [mhoban/rainbow_bridge#119]
In the following code in `collapse_taxonomy.R`, if either nodes or taxid lineage dump file are missing, it will error out.  The `|` in the `if` should be  `&&`.  I added error handling if only one or the other exists.  Both should exist, but I did run into this because an earlier version did not use taxid lineage dump.

```r
if (file_exists(nodes_dump) | file_exists(taxid_lineage_dump)) {
  lca_getter <- LCA$new(nodes = nodes_dump, merged = merged_dump, taxid_lineage = taxid_lineage_dump)
  lca <- TRUE
}
```

```r
if (file_exists(nodes_dump) && file_exists(taxid_lineage_dump)) {
  lca_getter <- LCA$new(nodes = nodes_dump, merged = merged_dump, taxid_lineage = taxid_lineage_dump)
  lca <- TRUE
} else {
  missing_files <- c()
  if (!file_exists(nodes_dump)) {
    missing_files <- c(missing_files, "nodes_dump")
  }
  if (!file_exists(taxid_lineage_dump)) {
    missing_files <- c(missing_files, "taxid_lineage_dump")
  }
  stop(paste("Error: The following file(s) are missing:", paste(missing_files, collapse = ", ")))
}
```

**Comment by mhoban** [comment]
Are you seeing an error? The `LCA` class is designed to work with *either* a `nodes.dmp` file *or* a `taxidlineage.dmp` file (mostly just because I first wrote it to use nodes and then realized that taxidlineage was right there and would work faster). 

This section controls whether the script retrieves the `taxid` of the common ancestor.

**Comment by cbird808** [comment]
If you don't have both, the way the script is written, it will throw an error

**Comment by cbird808** [comment]
I stand corrected, the error I encountered was because the var `taxid_lineage_dump` didn't exist.  that should not happen within the normal running of rainbow_bridge
