### ISSUE TITLE
Issues with degenerate bases in primers

### ISSUE THREAD

**Issue by ericgarciaresearch** [mhoban/rainbow_bridge#126]
Hi @mhoban ,

I have been having issues running the ngsfilter in a dataset that has degenerate bases in the primers. For example:

#assay  samples tags    forward_primer  reverse_primer
Leray-COI       194732  :       ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTAIACYTCIGGRTGICCRAARAAYCA    GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTGGWACWGGWTGAACWGTWTAYCCYCC
Leray-COI       194733-A1-S1    :       ACACTCTTTCCCTACACGACGCTCTTCCGATCTTTAIACYTCIGGRTGICCRAARAAYCA    GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTGGWACWGGWTGAACWGTWTAYCCYCC

I see you have issue #76 about replacing "I"s with "N"s. I have done this but this is not working for me. I have further change those Ns to Rs (so my primers won't have Is or Ns, only Rs, Ws Ys) but that still doesn't work.

Do you know if only "Is" are a problem (in which case I would have a separate issue)? and have you found a solution, work around?

Thanks!

**Comment by mhoban** [comment]
Can you post the error you're receiving? In my experience ngsfilter supports any nucleotide base in the IUPAC code (see [here](https://pythonhosted.org/OBITools/iupac.html?highlight=iupac))

**Comment by mhoban** [comment]
I tried a very simple test run using the primers you posted and didn't get any errors, but of course they didn't match anything because I don't have reads that were generated using those primers. 

All I did was replace I's with N's in the primers you posted.

**Comment by ericgarciaresearch** [comment]
Hi, sorry late reply. You were right, the pipeline is now working. I had some inconsistencies in the way I was formatting the barcode file and had some extra bases in the actual primer sequences. Running smoothly after changing Is for Ns

**Comment by mhoban** [comment]
Closing since this seems no longer to be an issue. As an aside, as of the recently-merged pull request (#128), the pipeline will automatically convert I to N in primer sequences.
