### ISSUE TITLE
`filter_uncultured` in `collapse_taxonomy.R`

### ISSUE THREAD

**Issue by cbird808** [mhoban/rainbow_bridge#99]
Hi @mhoban ,

While it's probably best for users to filter their blast db prior to blasting, given that you have the `filter_uncultured` option in `collapse_taxonomy.R`, it could be useful to change the option/argument from `T/F` to the regex pattern.  For example, some might want to remove "sp."  or some other term prior to determining the lca.  As you can see below, I had some output from an unfiltered db and I didn't want "Actinopterygii sp." and the like to skew the LCA to be too pessimistic with the caveat that there may be some small portion of valid Genus sp. taxids that I'm missing out on.

```r
# filter out any uncultured, environmental, etc.
if (filter_uncultured) {
  filtered <- filtered %>%
    # filter(if_all(domain:species,~!replace_na(str_detect(.,"uncultured|environmental sample|clone|synthetic"),FALSE)))  #CEB
    filter(if_all(domain:species,~!replace_na(str_detect(.,"uncultured|environmental sample|clone|synthetic| [Ss][Pp]+\\. *"),FALSE))) #CEB
}
```

**Comment by mhoban** [comment]
This is a good suggestion, and it's one I've had on my list for a while now. The current functionality is another holdover from the original eDNAFlow pipeline.

I'll change the option to accept a regex.

**Comment by mhoban** [comment]
```r
option_list <- list(
  ...
  make_option(c("-t", "--taxon-filter"), action="callback", default=NA, type='character', help="Regex to filter taxa (e.g., uncultured/synthetic/environmental sequences)",callback=na_opt),
  make_option(c("-c", "--case-insensitive"), action="store", default=FALSE, type='logical', help="Perform case-insensitve taxon filtering"),
  ...
)
...
taxon_filter <- opt$options$taxon_filter
ignore_case <- opt$options$case_insensitive
```
```r
# filter out any uncultured, environmental, etc.
if (!is.na(taxon_filter)) {
  filtered <- filtered %>%
    filter(if_all(domain:species,~!replace_na(str_detect(.,regex(taxon_filter,ignore_case = ignore_case)),FALSE))) 
}
```

**Comment by mhoban** [comment]
This should now be addressed (and merged into main)
